import Config

# Configure your database
# Reads from environment variables set in .env (when using Docker)
config :fractal, Fractal.Repo,
  username: System.get_env("DB_USER") || "root",
  password: System.get_env("DB_PASSWORD") || "",
  hostname: System.get_env("DB_HOST") || "localhost",
  database: System.get_env("DB_NAME") || "fractal_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("DB_POOL") || "10")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fractal, FractalWeb.Endpoint,
  # Bind to 0.0.0.0 for Docker, 127.0.0.1 for local development
  http: [
    ip: {0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "PWwTDVz2+R1jh2NQxRSQ5H6IQ4fKlVvYg4D35ALrQKPlSVKv6YZhsEDX4qNXHK9/",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :fractal, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure Valkey (Redis) connection
config :fractal, :redis_url, System.get_env("REDIS_URL") || "redis://localhost:6379"

# Configure Redpanda/Kafka brokers
config :fractal,
       :kafka_brokers,
       String.split(System.get_env("KAFKA_BROKERS") || "localhost:9092", ",")

# Configure Guardian JWT
config :fractal, Fractal.Guardian,
  issuer: "fractal",
  secret_key: System.get_env("JWT_SECRET") || "dev-jwt-secret-change-in-production"
